INSERT INTO guestbook.comments (id, email_id, comment) VALUES (1, 3, '<p>She wrote him a long letter, but he didn''t read it.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (2, 3, '<p>How was the math test?</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (3, 1, '<p>The stranger officiates the meal.Mary plays the piano.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (4, 1, '<p>Cats are good pets, for they are clean and are not noisy.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (5, 3, '<p>Sometimes it is better to just walk away from things and go back to them later when you’re in a better frame of mind.This is a Japanese doll.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (6, 3, '<p>He turned in the research paper on Friday; otherwise, he would have not passed the class.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (7, 1, '<p>Sixty-Four comes asking for bread.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (8, 1, '<p>I hear that Nancy is very pretty.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (12, 1, '<p>Last Friday in three week’s time I saw a spotted striped blue worm shake hands with a legless lizard.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (13, 3, '<p>The memory we used to share is no longer coherent.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (14, 1, '<p>He didn’t want to go to the dentist, yet he went anyway.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (15, 3, '<p>Please wait outside of the house.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (16, 1, '<p>Abstraction is often one floor above you.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (17, 1, '<p>Where do random thoughts come from?</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (18, 1, '<p>They got there early, and they got really good seats.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (19, 3, '<p>Kotlin is good, but i need to learn java first</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (20, 1, '<p>I will never be this young again. Ever. Oh damn… I just got older.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (21, 3, '<p>She did not cheat on the test, for it was not the right thing to do.
    We have never been to Asia, nor have we visited Africa.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (22, 3, '<p>Cats are good pets, for they are clean and are not noisy.The body may perhaps compensates for the loss of a true metaphysics.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (23, 1, '<p>I hear that Nancy is very pretty.I checked to make sure that he was still alive.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (24, 1, '<p>I often see the time 11:11 or 12:34 on clocks.A purple chicken and a green donkey flew a kite in the middle of the night and ended up sunburnt.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (25, 1, '<p>Last Friday in three week’s time I saw a spotted striped blue worm shake hands with a legless lizard.Two seats were vacant.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (26, 3, '<p>The waves were crashing on the shore; it was a lovely sight.My Mum tries to be cool by saying that she likes all the same things that I do.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (27, 3, '<p>I often see the time 11:11 or 12:34 on clocks.It was getting dark, and we weren’t there yet.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (28, 3, '<p>I''d rather be a bird than a fish.I want more detailed information.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (29, 3, '<p>I was very proud of my nickname throughout high school but today- I couldn’t be any different to what my nickname was.There were white out conditions in the town; subsequently, the roads were impassable.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (30, 1, '<p>This is a Japanese doll.Italy is my favorite country; in fact, I plan to spend two weeks there next year.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (31, 1, '<p>If you like tuna and tomato sauce- try combining the two. It’s really not as bad as it sounds.I''d rather be a bird than a fish.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (32, 3, '<p>I want to buy a onesie… but know it won’t suit me.Writing a list of random sentences is harder than I initially thought it would be.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (33, 1, '<p>There was no ice cream in the freezer, nor did they have money to go to the store.I really want to go to work, but I am too sick to drive.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (34, 3, '<p>How was the math test?Cats are good pets, for they are clean and are not noisy.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (35, 1, '<p>Where do random thoughts come from?He ran out of money, so he had to stop playing poker.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (36, 1, '<p>I am never at home on Sundays.She was too short to see over the fence.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (37, 3, '<p>Malls are great places to shop; I can find everything I need under one roof.Tom got a small piece of pie.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (38, 3, '<p>He told us a very exciting adventure story.The body may perhaps compensates for the loss of a true metaphysics.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (39, 3, '<p>This is the last random sentence I will be writing and I am going to stop mid-sent.A purple pig and a green donkey flew a kite in the middle of the night and ended up sunburnt.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (40, 1, '<p>I''d rather be a bird than a fish.If I don’t like something, I’ll stay away from it.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (41, 3, '<p>If you like tuna and tomato sauce- try combining the two. It’s really not as bad as it sounds.She advised him to come back at once.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (42, 1, '<p>She works two jobs to make ends meet; at least, that was her reason for not having time to join us.Last Friday in three week’s time I saw a spotted striped blue worm shake hands with a legless lizard.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (43, 3, '<p>I would have gotten the promotion, but my attendance wasn’t good enough.Sixty-Four comes asking for bread.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (44, 1, '<p>There were white out conditions in the town; subsequently, the roads were impassable.Should we start class now, or should we wait for everyone to get here?</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (45, 1, '<p>Writing a list of random sentences is harder than I initially thought it would be.Wow, does that work?</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (46, 1, '<p>The waves were crashing on the shore; it was a lovely sight.He told us a very exciting adventure story.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (47, 3, '<p>When I was little I had a car door slammed shut on my hand. I still remember it quite vividly.What was the person thinking when they discovered cow’s milk was fine for human consumption… and why did they do it in the first place!?</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (48, 3, '<p>I really want to go to work, but I am too sick to drive.Wednesday is hump day, but has anyone asked the camel if he’s happy about it?</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (49, 3, '<p>Lets all be unique together until we realise we are all the same.Don''t step on the broken glass.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (50, 1, '<p>Everyone was busy, so I went to the movie alone.I am counting my calories, yet I really want dessert.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (51, 3, '<p>If Purple People Eaters are real… where do they find purple people to eat?The clock within this blog and the clock on my laptop are 1 hour different from each other.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (52, 1, '<p>I was very proud of my nickname throughout high school but today- I couldn’t be any different to what my nickname was.I am happy to take your donation; any amount will be greatly appreciated.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (53, 3, '<p>She borrowed the book from him many years ago and hasn''t yet returned it.I often see the time 11:11 or 12:34 on clocks.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (54, 1, '<p>I hear that Nancy is very pretty.How was the math test?</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (55, 3, '<p>The body may perhaps compensates for the loss of a true metaphysics.I want to buy a onesie… but know it won’t suit me.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (56, 3, '<p>It was getting dark, and we weren’t there yet.I really want to go to work, but I am too sick to drive.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (57, 3, '<p>Everyone was busy, so I went to the movie alone.She only paints with bold colors; she does not like pastels.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (58, 1, '<p>She did not cheat on the test, for it was not the right thing to do.New Year is coming.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (59, 1, '<p>He didn’t want to go to the dentist, yet he went anyway.I really want to go to work, but I am too sick to drive.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (60, 1, '<p>I am never at home on Sundays.Wow, does that work?</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (61, 3, '<p>I want more detailed information.Someone I know recently combined Maple Syrup & buttered Popcorn thinking it would taste like caramel popcorn. It didn’t and they don’t recommend anyone else do it either.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (62, 3, '<p>The book is in front of the table.He didn’t want to go to the dentist, yet he went anyway.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (63, 1, '<p>I want to buy a onesie… but know it won’t suit me.I am never at home on Sundays.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (64, 1, '<p>There was no ice cream in the freezer, nor did they have money to go to the store.She borrowed the book from him many years ago and hasn''t yet returned it.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (65, 3, '<p>There were white out conditions in the town; subsequently, the roads were impassable.Check back tomorrow; I will see if the book has arrived.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (66, 3, '<p>A song can make or ruin a person’s day if they let it get to them.She only paints with bold colors; she does not like pastels.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (67, 3, '<p>Someone I know recently combined Maple Syrup & buttered Popcorn thinking it would taste like caramel popcorn. It didn’t and they don’t recommend anyone else do it either.How was the math test?</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (68, 1, '<p>The mysterious diary records the voice.Rock music approaches at high velocity.</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (69, 1, '<p>Yeah, I think it''s a good environment for learning English.Wow, does that work?</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (70, 3, '<p>Italy is my favorite country; in fact, I plan to spend two weeks there next year.What was the person thinking when they discovered cow’s milk was fine for human consumption… and why did they do it in the first place!?</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (71, 3, '<p>I hear that Nancy is very pretty.If the Easter Bunny and the Tooth Fairy had babies would they take your teeth and leave chocolate for you?</p>');
INSERT INTO guestbook.comments (id, email_id, comment) VALUES (72, 3, '<p>The shooter says goodbye to his love.If the Easter Bunny and the Tooth Fairy had babies would they take your teeth and leave chocolate for you?</p>');
INSERT INTO guestbook.users (id, email, password, phone) VALUES (1, 'slier81@gmail.com', '$2a$10$LXj3itSa.l7yocmlSXfEUeNbuHTtdww6hbLOJc4RyhWg2Bq0I5iVi', '0136175880');
INSERT INTO guestbook.users (id, email, password, phone) VALUES (2, 'ak@gmail.com', '$2a$10$OFQpUb4fhQh27MyILpbZPOfIg9rzCMQb2UFLhu8lHVkx79QKZmINW', '8759073');
INSERT INTO guestbook.users (id, email, password, phone) VALUES (3, 'sobri@mail.com', '$2a$10$f9MAqnLm0UHXbqhOOLqwUur9Je16WhGL9NTqKNGFLatF4D.brigz6', '0174912480');
INSERT INTO guestbook.users (id, email, password, phone) VALUES (8, 'sobri23@mail.com', '$2a$10$56OMqGqbuIiU0lRof0WLveQTlth.4331oSCV098yzD4oiYwexpDP6', '0136175880');